services:
  api:
    build: .
    container_name: flask-server
    depends_on:
      - mysql
    ports:
      - '5001:5000'
    environment:
      HBNB_API_HOST: '0.0.0.0'
      HBNB_API_PORT: 5000
    volumes:
      - mysql-db:/var/lib/mysql
      - ./file.json:/file.json
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always                       # always restart
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'hbnb_dev_db'
      MYSQL_USER: 'hbnb_dev'
      MYSQL_PASSWORD: 'hbnb_dev_pwd'
    ports:
      - '3307:3306'                       # host port 3307 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
      - ./setup_mysql_dev.sql:/setup_mysql_dev.sql
      - ./setup_mysql_test.sql:/setup_mysql_test.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
        mysql-db:
